language: python
python:
  - "3.7"
# Command to install dependencies
install:
  - pip install -r requirements.txt
# Command to run tests
script:
  - coverage run --source=app -m pytest app/tests/
after_success:
  # Publish coverage to coveralls
  - coveralls
  # Generate coverage report in xml format
  - coverage xml

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml